name: Deploy to Elasticbeanstalk

on:
  workflow_dispatch:
    inputs:
      commit:
        description: "branch"
        required: true

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm' 
      - run: npm ci
      - run: npm run lint   
      - run: npm run test      

  build_and_deploy:
    runs-on: ubuntu-latest
    needs: lint_and_test
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: '${{ github.event.inputs.commit }}'  

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - run: npm ci
      - run: npm run build --if-present

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: meta-integration-notify
          environment_name: Metaintegrationnotify-env
          version_label:  ${{ github.event.inputs.commit }}
          region: ${{ secrets.AWS_DEFAULT_REGION }}
          deployment_package: deploy.zip
          existing_bucket_name: ${{ secrets.AWS_BUCKET_NAME }}

      