name: Deploy to Elasticbeanstalk

on:
  push:
    branches:
      - main

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm' 
      - run: npm ci
      - run: npm run lint   
      - run: npm run test      

  build_and_deploy:
    runs-on: ubuntu-latest
    needs: lint_and_test
    outputs:
      sha_short: ${{ steps.vars.outputs.sha_short }}
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Declare variables
        id: vars
        shell: bash
        run: echo "::set-output name=sha_short::$(git rev-parse --short ${GITHUB_SHA})" 

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - run: npm ci
      - run: npm run build --if-present

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: meta-integration-notify
          environment_name: Metaintegrationnotify-env
          version_label:   ${{ steps.vars.outputs.sha_short }}
          region: ${{ secrets.AWS_DEFAULT_REGION }}
          deployment_package: deploy.zip
          existing_bucket_name: ${{ secrets.AWS_BUCKET_NAME }}

      